# Generated by Django 3.2 on 2021-04-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('project_type', models.CharField(choices=[('BE', 'Back-End'), ('Fr', 'Front-End'), ('IOS', 'IOS'), ('An', 'Android')], max_length=100, verbose_name='Type')),
                ('author_user_id', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('tag', models.CharField(choices=[('B', 'BUG'), ('A', 'AMÉLIORATION'), ('T', 'TÂCHE')], max_length=100, verbose_name='Balise')),
                ('priority', models.CharField(choices=[('F', 'FAIBLE'), ('M', 'MOYENNE'), ('E', 'ÉLEVÉE')], max_length=100, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('AF', 'À faire'), ('EC', 'En cours'), ('T', 'Terminé')], max_length=100, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('assigned_user_id', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'verbose_name': 'Problème',
                'verbose_name_plural': 'Problèmes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='api.issue')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('C', 'Création'), ('R', 'Lecture'), ('U', 'Modification'), ('D', 'Suppression')], max_length=100)),
                ('role', models.CharField(choices=[('A', 'Auteur'), ('R', 'Responsable'), ('C', 'Créateur')], max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'unique_together': {('user_id', 'project_id')},
            },
        ),
    ]
