# Generated by Django 3.2 on 2021-04-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210423_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
