# Generated by Django 3.2 on 2021-04-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_contributor_issue_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
