# Generated by Django 3.2 on 2021-04-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment_contributor_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project_id',
        ),
    ]
