# Generated by Django 3.2 on 2021-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_comment_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Back-End', 'Back-End'), ('Front-End', 'Front-End'), ('Full-Stack', 'Full-Stack'), ('IOS', 'IOS'), ('Android', 'Android')], max_length=100, verbose_name='Type'),
        ),
    ]
