# Generated by Django 3.2 on 2021-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, choices=[('Auteur', 'Auteur'), ('Responsable', 'Responsable'), ('Créateur', 'Créateur'), ('Contributeur', 'Contributeur')], max_length=100, null=True),
        ),
    ]
